baseURL = "https://example.com/"
languageCode = "en-us"
title = "Alimjan Mettursun"
theme = "resume"

[params]
    firstName = "Alimjan"
    lastName = "mettursun"
    address = "Beijing, China"
    phone = "18888888888"
    contactNote = "Dev Tools Engineer"
    profileImage = "img/alim_profile.png"
    email = "almett@outlook.com"
    description = "Software development Engineer with 4 years of experience mainly on back-end development. Certain amount offront-end and mobile app development."
    favicon = "images/favicon.ico"
    # what sections
    showSkills = true
    showProjects = true
    showOpenSource = false
    showPublications = false
    showExperience = true
    showEducation = true

    showQr = true

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/alimjan-mettursun-bb85385b/"


[[params.handles]]
    name = "GitHub"
    link = "https://github.com/maninwindow"

[[params.handles]]
    name = "Stack Overflow"
    link = "https://stackoverflow.com/users/2828685/almett"
    icon = "stack-overflow"
